const { onRequest, runWith } = require("firebase-functions/v2/https");
const express = require("express");
const dotenv = require("dotenv");
const bodyParser = require("body-parser");
const cors = require("cors");
const AppRouter = require("./Routes/app_routes");
const db = require("./config/db");
dotenv.config();
const app = express();
app.use(bodyParser.json());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors({ origin: true }));
app.use(AppRouter);
exports.api = onRequest({ timeoutSeconds: 300, memory: "512MB" }, app);